name: Run Tests

on:
  push:
    branches:
      - main  # Jab main branch pe push ho

jobs:
  test:
    runs-on: ubuntu-latest  # Ye environment batata hai jahan pe code run hoga

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Code ko checkout karna

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # Node.js version

      - name: Install Dependencies
        run: npm install  # Dependencies install karna

      - name: Run Tests
        run: npm test  # Tests run karna
